### ISSUE TITLE
Various improvements

### ISSUE THREAD

**Issue by dlecan** [unik-name/uns-delegates-website#13]
Proposals for various improvements

- Delegate template
   - [x] Remove unikid from all delegate template frontmatters and deduce them from the path

- Delegate page (public and embedded)
   - [x] Update the meta description: pick the first 150 chars to the README.md of the profile. Break **before** the last word included in the 150 chars limit
   - [x] Update the title: `$explicitValue's delegate profile`
     - [x] HTML title
     - [x] open-graph title
   - [x] Update the data generated by https://github.com/lorisleiva/vuepress-plugin-seo: the author should be the delegate (name and Twitter account)
   - [x] Add a call-to-action `Support this delegate on your My Unikname App` with a link to `https://my.unikname.app/`
   - [x] Center footer on delegate page (tested on ios safari) point_down

- Home page
   - [x] non-forging delegates should have a red light card
   - [x] non-elected delegates should have a light blue card
   - [x] status of the non-forging delegates should be: `slowing down the network since <delay> hours/days`

**Comment by Nigui** [comment]
- [ ] footer non centré sur la page d'un délégué (testé sur ios safari)
- [ ] possibilité d'ajouter des images en markdown ? 
- [ ] un bouton d'action type "support delegate" qui pointe vers MyUniknameApp ?

![IMG_55BADD9D5405-1](https://user-images.githubusercontent.com/6088236/120780351-4f9d3a80-c528-11eb-9a18-002830cef227.jpeg)

**Comment by dlecan** [comment]
> Could we give delegate opportunity to add images in markdown file ?

Already possible, doesn't it?

**Comment by dlecan** [comment]
Every thing has been done
